spring.application.name=billingservice
spring.config.import=optional:configserver:http://configserver:8888
spring.profiles.active=default
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5